"""empty message

Revision ID: 0b52fa445923
Revises: 8e794cfd2873
Create Date: 2019-05-13 09:18:17.324346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b52fa445923'
down_revision = '8e794cfd2873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answers_id', sa.Integer(), nullable=False))
    op.drop_constraint('questions_answer_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'answers', ['answers_id'], ['id'])
    op.drop_column('questions', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_answer_id_fkey', 'questions', 'answers', ['answer_id'], ['id'])
    op.drop_column('questions', 'answers_id')
    # ### end Alembic commands ###
