"""empty message

Revision ID: 318a3799ad6c
Revises: e3df006a532e
Create Date: 2019-05-13 10:43:58.447740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318a3799ad6c'
down_revision = 'e3df006a532e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.drop_constraint('questions_answers_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'answers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_answers_id_fkey', 'questions', 'answers', ['answers_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
