"""empty message

Revision ID: 32450280245d
Revises: 496268fac2ab
Create Date: 2019-05-14 16:33:03.160277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32450280245d'
down_revision = '496268fac2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('response_id', sa.Integer(), nullable=False))
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['response_id'], ['id'])
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    op.drop_column('answers', 'response_id')
    # ### end Alembic commands ###
