"""empty message

Revision ID: 47670959cd13
Revises: 40df541d79b8
Create Date: 2019-05-28 14:38:45.802936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47670959cd13'
down_revision = '40df541d79b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
