"""empty message

Revision ID: 496268fac2ab
Revises: 717b15105ea5
Create Date: 2019-05-13 19:57:08.583476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496268fac2ab'
down_revision = '717b15105ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'slug')
    # ### end Alembic commands ###
