"""empty message

Revision ID: 4f63636805fd
Revises: 77490dc75617
Create Date: 2019-05-14 16:57:30.868397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f63636805fd'
down_revision = '77490dc75617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'response_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'response_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
