"""empty message

Revision ID: 717b15105ea5
Revises: d331b5aac0a2
Create Date: 2019-05-13 11:27:04.760143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717b15105ea5'
down_revision = 'd331b5aac0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_id_key', 'questions', type_='unique')
    op.create_unique_constraint(None, 'questions', ['question'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.create_unique_constraint('questions_id_key', 'questions', ['id'])
    # ### end Alembic commands ###
