"""empty message

Revision ID: 793cb9a65116
Revises: 47670959cd13
Create Date: 2019-05-28 21:46:38.560289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793cb9a65116'
down_revision = '47670959cd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responses', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
