"""empty message

Revision ID: 8e794cfd2873
Revises: 0cb75846f31f
Create Date: 2019-05-12 09:36:46.379527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e794cfd2873'
down_revision = '0cb75846f31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_answer_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'answers', ['answer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_answer_id_fkey', 'questions', 'questions', ['answer_id'], ['id'])
    # ### end Alembic commands ###
