"""empty message

Revision ID: d331b5aac0a2
Revises: 318a3799ad6c
Create Date: 2019-05-13 11:09:48.006491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd331b5aac0a2'
down_revision = '318a3799ad6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questions', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    # ### end Alembic commands ###
