"""empty message

Revision ID: e3df006a532e
Revises: 0b52fa445923
Create Date: 2019-05-13 09:32:27.213090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3df006a532e'
down_revision = '0b52fa445923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'answers_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'answers_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
