"""empty message

Revision ID: e545317dcec4
Revises: 4f63636805fd
Create Date: 2019-05-14 23:07:44.265492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e545317dcec4'
down_revision = '4f63636805fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('a', sa.String(), nullable=False))
    op.add_column('answers', sa.Column('b', sa.String(), nullable=False))
    op.add_column('answers', sa.Column('c', sa.String(), nullable=False))
    op.add_column('answers', sa.Column('d', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'd')
    op.drop_column('answers', 'c')
    op.drop_column('answers', 'b')
    op.drop_column('answers', 'a')
    # ### end Alembic commands ###
